homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.review, name='review'),
    path('review/create', views.review_create, name='review_create'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),

]

homepage/models.py
from django.db import models


class Review(models.Model):

    fill = models.CharField(max_length=200)

    def __str__(self):
        return "{}. {}".format(self.id, self.activity)

homepage/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['fill']
        widgets = {
            'fill':forms.TextInput(attrs={'placeholder':'Masukkan kritik dan saran'}),
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import Review
from . import forms

def review(request):
    reviews = Review.objects.all().order_by('id')
    return render(request, 'result.html', {'reviews': reviews})

def review_create(request):
    if request.method == 'POST':
        form = forms.ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:review')

    else:
        form = forms.ScheduleForm()
    return render(request, 'input.html', {'form': form})

homepage/templates/input.html
 <form class="css" action="{% url 'homepage:review_create' %}" method="post">
    {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
                <div class="form-group col-sm-10 tag">
                    {% for fields in form %}
                        {{ fields.label_tag }}
                        <br>
                        {{ fields }}
                    {% endfor %}
                </div>
            </div>
        <div class="form-row">
            <input type="submit" class="btn btn-primary float-right" value="Add">
        </div>
</form>

homepage/templates/result.html
{% for review in reviews %}
    <tr>
        <td>{{ review.fill }}</td>
    </tr>
{% endfor %}
<a href="{% url 'homepage:review_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>